[package]
name = "home_logic"
version = "0.1.0"
authors = ["Athiwat Chunlakhan <athiwatc@gmail.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
diesel = { version = "1.1", features = ["sqlite", "r2d2"] }
dotenv = "0.11.0"